#!/bin/bash

echo $(hostname): $(
	(
	for ((i=0; i < 60; i+=1)); do 
		ps -u root -o %cpu,pid,user,numa,psr,args | awk '/freezable_power/ { print $5 }'; 
		sleep 1; 
	done
	) | sort -n | uniq | xargs)
